# -*- coding: utf-8 -*-
"""wk1_work.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MlI3NUw6sapNt_eJybi_11aeb2NEdycR
"""

paper_thickness = 0.00008
folding_num = 43

def folded_paper_calculator(paper_thickness, folding_num):
  result = paper_thickness * 2**folding_num
  return result

print(folded_paper_calculator(paper_thickness, folding_num))

"""## 問題１"""

def q1():
  """
  紙を1回折った時の厚さを計算するコード
  """
  THICKNESS = 0.00008
  folded_thickness = THICKNESS*2**43
  print("厚さ： {}メートル".format(folded_thickness))

q1()

"""## 問題２"""

# メートルをキロメートルに変換して小数点以下2桁で表示する
print("厚さ： {:.2f}万キロメートル".format(folded_thickness/1000/10000))

"""## 問題３"""

def q3():  
  x = 2
  for i in range(42):
    x *= 2
  folded_thickness = THICKNESS*x
  print("厚さ： {:.2f}万キロメートル".format(folded_thickness/1000/10000))

q3()

"""## 問題４"""

import time

start = time.time()
q1()
elapsed_time = time.time() - start
print("time : {}[s]".format(elapsed_time))

start = time.time()
q3()
elapsed_time = time.time() - start
print("time : {}[s]".format(elapsed_time))

"""## 問題５"""

def q5():  
  x = 1
  xlist = []
  xlist.append(THICKNESS)
  for i in range(43):
    x *= 2
    y = THICKNESS*x
    xlist.append(y)
  return xlist

xlist = q5()
print(len(xlist))

"""## 問題６"""

# Commented out IPython magic to ensure Python compatibility.
"""
グラフを表示する。タイトルと軸ラベル名付き。
"""
import matplotlib.pyplot as plt
# %matplotlib inline
plt.title("thickness of folded paper")
plt.xlabel("number of folds")
plt.ylabel("thickness[m]")
plt.plot(xlist) # 「リスト名」のところにリストの変数名を入れる
plt.show()

"""## 問題７"""

"""
Black折れ線グラフを表示する。
"""
plt.title("thickness of folded paper")
plt.xlabel("number of folds")
plt.ylabel("thickness[m]")
plt.plot(xlist, color='black')
plt.show()

"""
point markerグラフを表示する。
"""
plt.title("thickness of folded paper")
plt.xlabel("number of folds")
plt.ylabel("thickness[m]")
plt.plot(xlist, marker='.')
plt.show()

"""
pixel markerグラフを表示する。
"""
plt.title("thickness of folded paper")
plt.xlabel("number of folds")
plt.ylabel("thickness[m]")
plt.plot(xlist, marker=',')
plt.show()

"""
circle markerグラフを表示する。
"""
plt.title("thickness of folded paper")
plt.xlabel("number of folds")
plt.ylabel("thickness[m]")
plt.plot(xlist, marker='o')
plt.show()

"""
greenグラフを表示する。
"""
plt.title("thickness of folded paper")
plt.xlabel("number of folds")
plt.ylabel("thickness[m]")
plt.plot(xlist, color='g')
plt.show()

plt.title("thickness of folded paper")
plt.xlabel("number of folds")
plt.ylabel("thickness[m]")
plt.tick_params(labelsize=20) # 軸の値に関する設定を行う
plt.plot(xlist)
plt.show()

